#include <stdio.h>
int main()
{
int num = 5;
num = num + 1;
int res;
res = 0;
res = res + 1;
num++;
res++;
res = num;
printf("%d\n",res);
int num1 = 45;
num1++;
int num2 = 34;
num2++;
num1 = num1 + num2;
num2++;
num2 = num1++;
printf("The value of num1 is : %d\n",num2);
printf("The value of num2 is : %d\n",num1);
int num2 = 0;
num2++;
num2++;
num2++;
int r;
r = num2;
num2= 0;
r = r + 1;
r = r * 2;
r++;
printf("%d",r);
printf("%d",num2);
int num2 = 0;
num2--;
num2--;
num2--;
int r;
r = num2;
num1= 0;
r = r + 1;
r = num2;
r = r * 2;
r++;
printf("%d",r);
printf("%d",num2);
int num2 = 0;
int res;
res = num2-- ;
res = res * 2;
int m;
m = 3 + res - 2 * 3;
printf("%d\n%d\n",m,res);
int num2 = 0;
int r = num2 + 1;
num1++;
r = num2 + ( 3 * 4) + 4 * 3;
printf("%d", r);
int num2 = 0;
num1 = 4 > 5;
num1 = num1 + 1;
int res = num1 % 2;
res++;
res--;
num1 = res++;
printf("%d\n",res);
printf("%d\n",num1);
int num1 = 0;
int res = num1 / 2 * 3 + 3 && 3 || 4 + 2 ;
res = res + 1;
res--;
num1 = res * 4 ;
num1 = 4 * (res++);
printf("The num1 value is: %d\nThe res value
is : %d\n",num1,res);
int num1 = 6 * 4 + 4;
num1 = num1 > 0 && 4;
num1++;
int num2 = num1;
int num3 = num2++;
num1 = num3--;
num2 = num3++;
int res = num1 + num2;
printf("The res is : %d\n",res);
printf("The num1 is : %d\n",num1);
printf("The num2 is : %d\n",num2);
}